export {
    type AuroraComponentDefinition,
    type AuroraComponentModule,
    type AuroraConfig,
    type AuroraContext,
    type AuroraFooterConfig,
    type AuroraLayoutDefinition,
    type AuroraLayoutModule,
    type AuroraLayoutProps,
    type AuroraLink,
    type AuroraNavigationGroup,
    type AuroraNavigationItem,
    type AuroraNavigationLink,
    type AuroraPageConfig,
    type AuroraPageLinks,
    type AuroraPageMeta,
    type AuroraRuntimeNavigationItem,
    type AuroraSearchEntry,
    type AuroraSocialLink,
    type AuroraStaticPage,
    defineConfig,
} from './lib/config/config';
